export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const ADD = 'ADD';
export const SUBTRACT = 'SUBTRACT';
export const STORE_RESULT = 'STORE_RESULT';
export const SAVE_STATE = 'SAVE_STATE';
export const SAVE_STATE_TO_FILE = 'SAVE_STATE_TO_FILE';

export const PERSIST_STATE = 'PERSIST_STATE';

export const DELETE_RESULT = 'DELETE_RESULT';

export const BIN_START = "BIN_START";
export const BIN_STOP = "BIN_STOP";

export const PROGRAM_TYPE = "PROGRAM";
export const POORWEATHER_TYPE = "POORWEATHER";
export const BACKUP_TYPE = "BACKUP";


export const NIGHT_START = "NIGHT_START";
export const NIGHT_STOP = "NIGHT_STOP";

export const WEATHERLOSS = "WEATHERLOSS";
export const WEATHERLOSS_START = "WEATHERLOSS_START";
export const WEATHERLOSS_STOP = "WEATHERLOSS_STOP";

export const POORWTHPROG = "POORWTHPROG";
export const POORWTHPROG_START = "POORWTHPROG_START";
export const POORWTHPROG_STOP = "POORWTHPROG_STOP";

export const BACKUPPROG = "BACKUPPROG";
export const BACKUPPROG_START = "BACKUPPROG_START";
export const BACKUPPROG_STOP  = "BACKUPPROG_STOP";


export const TECHDOWNTIME = "TECHDOWNTIME";
export const TECHDOWNTIME_START = "TECHDOWNTIME_START";
export const TECHDOWNTIME_STOP = "TECHDOWNTIME_STOP";

export const CALIBRATION = "CALIBRATION";
export const CALIBRATION_START = "CALIBRATION_START";
export const CALIBRATION_STOP = "CALIBRATION_STOP";

export const OPENSHUTTER = "OPENSHUTTER";
export const CALC_OS_TNTIME = "CALC_OS_TNTIME";
export const UPDATE_POORWEATHER = "UPDATE_POORWEATHER";
export const UPDATE_BACKUP = "UPDATE_BACKUP";

export const HUMANERROR = "HUMANERROR";

export const PROGRAM_START = "PROGRAM_START";
export const PROGRAM_STOP = "PROGRAM_STOP";
export const PROGRAM_UPDATE = "PROGRAM_UPDATE";
export const DOWNTIME_UPDATE = "DOWNTIME_UPDATE";

export const UPDATE_TOTALS = 'UPDATE_TOTALS';

export const TEST_ACTION = "TEST_ACTION";
export const TEST_ACTION2 = "TEST_ACTION2";



export const FETCH_STATE = 'FETCH_STATE';
export const FETCH_STATE_PENDING = 'FETCH_STATE_PENDING';
export const FETCH_STATE_SUCCESS = 'FETCH_STATE_SUCCESS';
export const FETCH_DWNTIME_STATE_SUCCESS = 'FETCH_DWNTIME_STATE_SUCCESS';
export const FETCH_NIGHTS_STATE_SUCCESS = 'FETCH_NIGHTS_STATE_SUCCESS';
export const FETCH_TOTALS_STATE_SUCCESS = 'FETCH_TOTALS_STATE_SUCCESS';
export const FETCH_PROGRAMS_STATE_SUCCESS = 'FETCH_PROGRAMS_STATE_SUCCESS';
export const FETCH_RES_STATE_SUCCESS = 'FETCH_RES_STATE_SUCCESS';

export const FETCH_STATE_ERROR = 'FETCH_STATE_ERROR';


export const START_NTIMER = 'START_NTIMER';
export const STOP_NTIMER = 'STOP_NTIMER';
export const RESET_NTIMER = 'RESET_NTIMER';


export const UPDATE_APP_STATE = 'UPDATE_APP_STATE';