export const NIGHT_START = "NIGHT_START";
export const NIGHT_STOP = "NIGHT_STOP";

export const WEATHERLOSS_START = "WEATHERLOSS_START";
export const WEATHERLOSS_STOP = "WEATHERLOSS_STOP";

export const POORWTHPROG_START = "POORWTHPROG_START";
export const POORWTHPROG_STOP = "POORWTHPROG_STOP";

export const TECHDOWNTIME_START = "TECHDOWNTIME_START";
export const TECHDOWNTIME_STOP = "TECHDOWNTIME_STOP";

export const CALIBRATION_START = "CALIBRATION_START";
export const CALIBRATION_STOP = "CALIBRATION_STOP";

export const PROGRAM_START = "PROGRAM_START";
export const PROGRAM_STOP = "PROGRAM_STOP";